---
title: "SARIMA"
author: "Yuda Taufiqurahman Wenske_140610230087"
date: "2025-05-25"
output: pdf_document
---

```{r}
suppressPackageStartupMessages({
  library(fpp2)
  library(tidyverse)
  library(lmtest)
  library(urca)
  library(tseries)
  library(sarima)
  library(fracdiff)
})
```

```{r}
data <- ts(c(
  299728.55, 728001.54, 1473786.05, 1195082.94, 836142.83, 837326.74,
  1024002.89, 886827.33, 834176.52, 592588.4, 583845.45, 355849.51,
  247674.94, 324349.34, 1399151.01, 1656631.53, 786210.04, 646971.1,
  850948.77, 871335.04, 752680.61, 559023.12, 566848.06, 423133.66,
  261729.1, 163278.53, 423836.77, 1696126.86, 1275304.92, 644210.91,
  706354.49, 940312.2, 1079807.01, 750530.26, 630997.78, 444283.75,
  401495.02, 542939.77, 1340410.87, 1167476.96, 755057.2, 729855.69,
  1167556.65, 641696.59, 615201.95, 682706.24, 545923.54, 523252.6,
  423391.47, 464402.92, 1500151.45, 1340685.28, 656580.47, 757632.04,
  1022173.88, 759793.58, 800152.89, 724268.05, 593254.02, 391237.04,
  477312.18, 599116.5, 1322270.78, 1049983.11, 1027199.98, 746141.45,
  893429.64, 646621.01, 714231.51, 792892.37, 512287.05, 358553.62
),start=c(2018, 1), end=c(2023,12), frequency = 12)
data
```

```{r}
autoplot(data) +
  xlab("Bulan-Tahun") + ylab("Produksi Tanaman Padi Kabupaten/Kota menurut Bulan di Provinsi Jawa Barat")
```

```{r}
x = data
```

```{r}
Fungsiku <- function(x,d){
  n<-length(x)
  k<-round((n-1)/2)
  omega<-c()
  t<-c(1:n)
  md=matrix(0,nrow=k,ncol=n)
  mt=matrix(0,nrow=k,ncol=n)
  mdata=matrix(0,nrow=k,ncol=n)
  cosomega=matrix(0,nrow=k,ncol=n)
  md1=matrix(0,nrow=k,ncol=n)
  mt1=matrix(0,nrow=k,ncol=n)
  mdata=matrix(0,nrow=k,ncol=n)
  sinomega=matrix(0,nrow=k,ncol=n)
  for (i in 1:k)
  {
    omega[i]<-(2*pi*i)/n
    md[i,]<-omega[i]
    mt[i,]<-t
    mdata[i,]<-x[t]
  }
  cosomega<-mdata*cos(md*mt)
  sinomega<-mdata*sin(md*mt)
  a<-c()
  b<-c()
  periodogram<-c()
  for (i in 1:k)
  {
    a[i]<-(2/n)*sum(cosomega[i,])
    b[i]<-(2/n)*sum(sinomega[i,])
    
    periodogram[i]<-(a[i]^2+b[i]^2)
  }
  k<-which.max(periodogram)
  omega<-(2*pi*k)/n
  Periode<-(2*pi)/omega
  Thitung<-(max(periodogram))/sum(periodogram)
  Nbintang<-c(seq(5,50,by=5))
  galpha<-c(0.68377,0.444,0.33462,0.27040,0.22805,0.19784,0.17513,0.15738,0.14310,0.13135)
  Tabel<-cbind(Nbintang,galpha)
  Ttabel<-Tabel[10,2]
  if (Thitung>Ttabel){
    print('Data mengikuti pola musiman')
  } else {
    print('Data tidak mengikuti pola musiman')
  }
  Periode 
}

delta<-fdGPH(data,bandw.exp=0.5)$d
delta

if (delta>0.5){
  x<-diffseries(x,d=delta)
  Fungsiku(x,delta)
} else {
  Fungsiku(x,delta)}
```

```{r}
lambda <- BoxCox.lambda(data)
lambda
```

```{r}
# Test how many seasonality differences required
data %>%  nsdiffs()
```

```{r}
data_sd <- data %>% diff(lag=12) ;data_sd
```

```{r}
data_sd %>% nsdiffs()
```

```{r}
data_sd %>% adf.test()
```

```{r}
autoplot(data_sd)
```

```{r}
data_sd %>% ggtsdisplay() # p = 2; q = 2; P = 2; Q = 2
```

```{r}
n <- length(data);n
training <- data[1:60];training
testing <- data[61:72];testing
```

```{r}
model1 <- arima(training, order = c(0,0,2), seasonal = c(0,1,2))
model2 <- arima(training, order = c(2,0,0), seasonal = c(2,1,0))
model3 <- arima(training, order = c(2,0,2), seasonal = c(2,1,2))

c(AIC(model1),AIC(model2),AIC(model3))
```

```{r}
best_model <- model3 # Model with the lowest AIC
```

```{r}
coeftest(best_model)
```
```{r}
r <- residuals(best_model)
n	<- length(r) 
mean	<- mean(r)
sd	<- sd(r)
res	<- rnorm(n,mean,sd)

ks.test(r,res)
```

```{r}
Box.test(r,lag=1,type=c("Ljung-Box"))
```

```{r}
h	<- r^2
Box.test(h,lag=1,type=c("Ljung-Box"))
```

```{r}
autoplot(forecast(best_model,12))
```

```{r}
library(forecast)
library(Metrics)
# Forecast 
forecast_result <- forecast(best_model, h = 12) 
predicted <- as.numeric(forecast_result$mean) 
# Data aktual 
actual <- c(data[61:72]) 
actual
mape(actual, predicted) 
```

```{r}
model_auto<-auto.arima(data[1:60], seasonal = TRUE) 
model_auto 
```

```{r}
r2 <- residuals(model_auto)
n	<- length(r2) 
mean	<- mean(r2)
sd	<- sd(r2)
res	<- rnorm(n,mean,sd)

ks.test(r2,res)
```

```{r}
Box.test(r2,lag=1,type=c("Ljung-Box"))
```

```{r}
h	<- r2^2
Box.test(h,lag=1,type=c("Ljung-Box"))
```

```{r}
library(forecast)
library(Metrics)
# Forecast 
forecast_result2 <- forecast(model_auto, h = 12) 
predicted2 <- as.numeric(forecast_result2$mean) 
# Data aktual 
actual <- c(data[61:72]) 
actual
mape(actual, predicted2) 
```

```{r}
model_fix <- arima(data, order = c(2,0,2), seasonal = c(2,1,2))
model_fix
```

```{r}
forecast_result3 <- forecast(model_fix, h = 12) 
forecast_result3 
```

```{r}
autoplot(forecast_result3)
```